In [11]:
import pandas as pd
import numpy as np

In [12]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\kapoo\OneDrive\Desktop\Python_tutorials\Sales Automated Dashboard\SuperStoreOrders.csv\SuperStoreOrders.csv"
)

df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2.0,0.0,106.140,35.46,Medium,2011.0
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3.0,0.1,36.036,9.72,Medium,2011.0
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4.0,0.0,29.640,8.17,High,2011.0
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3.0,0.5,-26.055,4.82,High,2011.0
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5.0,0.1,37.770,4.70,Medium,2011.0

In [13]:
df.shape

(51293, 21)

In [14]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51293 entries, 0 to 51292
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51292 non-null  object
 1   order_date      51292 non-null  object
 2   ship_date       51292 non-null  object
 3   ship_mode       51292 non-null  object
 4   customer_name   51285 non-null  object
 5   segment         51292 non-null  object
 6   state           51292 non-null  object
 7   country         51286 non-null  object
 8   market          51292 non-null  object
 9   region          51292 non-null  object
 10  product_id      51292 non-null  object
 11  category        51292 non-null  object
 12  sub_category    51292 non-null  object
 13  product_name    51291 non-null  object
 14  sales           51284 non-null  object
 15  quantity        51292 non-null  float64
 16  discount        51292 non-null  float64
 17  profit          51284 non-null  float64
 18  shipping_cost   51292 non-null  float64
 19  order_priority  51292 non-null  object
 20  year            51292 non-null  float64
dtypes: float64(5), object(16)
memory usage: 8.2+ MB

In [16]:
df.describe()

           quantity     discount        profit  shipping_cost          year
count  51292.000000  51292.00000  51284.000000   51292.000000  51292.000000
mean       3.476624      0.14291     28.636171      26.375366   2012.777139
std        2.278759      0.21228    174.435796      57.295773      1.098966
min        1.000000      0.00000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.00000      0.000000       2.610000   2012.000000
50%        3.000000      0.00000      9.240000       7.790000   2013.000000
75%        5.000000      0.20000     36.810000      24.450000   2014.000000
max       14.000000      0.85000   8399.976000     933.570000   2014.000000

In [17]:
df.isnull().sum()

order_id          1
order_date        1
ship_date         1
ship_mode         1
customer_name     8
segment           1
state             1
country           7
market            1
region            1
product_id        1
category          1
sub_category      1
product_name      2
sales             9
quantity          1
discount          1
profit            9
shipping_cost     1
order_priority    1
year              1
dtype: int64

In [18]:
df.duplicated().sum()

np.int64(2)

In [19]:
before_rows = df.shape[0]

df = df.dropna(how='all')

after_rows = df.shape[0]

print("Rows removed:", before_rows - after_rows)

Rows removed: 1

In [20]:
before_rows = df.shape[0]

df = df.drop_duplicates()

after_rows = df.shape[0]

print("Duplicate rows removed:", before_rows - after_rows)

Duplicate rows removed: 2

In [21]:
df.duplicated().sum()

df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     7
segment           0
state             0
country           6
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      1
sales             8
quantity          0
discount          0
profit            8
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [22]:
print("Rows removed:", before_rows - after_rows)

Rows removed: 2

In [23]:
print("Duplicate rows removed:", before_rows - after_rows)

Duplicate rows removed: 2

In [24]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     7
segment           0
state             0
country           6
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      1
sales             8
quantity          0
discount          0
profit            8
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [25]:
before_rows = df.shape[0]

df = df.dropna(subset=[
    'customer_name',
    'product_name',
    'sales',
    'profit'
])

after_rows = df.shape[0]

print("Rows removed:", before_rows - after_rows)

Rows removed: 23

In [26]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           5
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [27]:
df.dtypes

order_id           object
order_date         object
ship_date          object
ship_mode          object
customer_name      object
segment            object
state              object
country            object
market             object
region             object
product_id         object
category           object
sub_category       object
product_name       object
sales              object
quantity          float64
discount          float64
profit            float64
shipping_cost     float64
order_priority     object
year              float64
dtype: object

In [28]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

ValueError: time data "13-01-2011" doesn't match format "%m/%d/%Y", at position 12. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [29]:
df[['order_date', 'ship_date']].head(10)

  order_date ship_date
0   1/1/2011  6/1/2011
1   1/1/2011  8/1/2011
2   1/1/2011  5/1/2011
3   1/1/2011  5/1/2011
4   1/1/2011  8/1/2011
5   1/1/2011  8/1/2011
6   2/1/2011  6/1/2011
7   3/1/2011  3/1/2011
8   3/1/2011  9/1/2011
9   3/1/2011  7/1/2011

In [30]:
df[df['order_date'].str.contains('-', na=False)][['order_date']].head(10)

     order_date
162  13-01-2011
163  13-01-2011
164  13-01-2011
165  13-01-2011
166  13-01-2011
167  13-01-2011
168  13-01-2011
169  13-01-2011
170  13-01-2011
171  13-01-2011

In [32]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    format='mixed',
    dayfirst=True
)

df['ship_date'] = pd.to_datetime(
    df['ship_date'],
    format='mixed',
    dayfirst=True
)

In [40]:
df.dtypes

order_id                  object
order_date        datetime64[ns]
ship_date         datetime64[ns]
ship_mode                 object
customer_name             object
segment                   object
state                     object
country                   object
market                    object
region                    object
product_id                object
category                  object
sub_category              object
product_name              object
sales                    float64
quantity                 float64
discount                 float64
profit                   float64
shipping_cost            float64
order_priority            object
year                     float64
dtype: object

In [34]:
df['sales'].head(10)

0    408
1    120
2     66
3     45
4    114
5     55
6    314
7    276
8    912
9    667
Name: sales, dtype: object

In [35]:
df['sales'].sample(10)

25336     28
9693      77
45445    252
4341     133
40683    116
44064    397
46026    115
21526    105
48095     50
19702      6
Name: sales, dtype: object

In [38]:
df['sales'] = pd.to_numeric(df['sales'], errors='coerce')

In [39]:
df['sales'].isnull().sum()

np.int64(2629)

In [41]:
# Month Number
df['Month'] = df['order_date'].dt.month

# Month Name
df['Month_Name'] = df['order_date'].dt.month_name()

# Quarter
df['Quarter'] = df['order_date'].dt.quarter

# Day Name
df['Day_Name'] = df['order_date'].dt.day_name()

# Day Number
df['Day'] = df['order_date'].dt.day

# Week Number
df['Week'] = df['order_date'].dt.isocalendar().week

In [42]:
df[['order_date',
    'Month',
    'Month_Name',
    'Quarter',
    'Day_Name',
    'Week']].head()

  order_date  Month Month_Name  Quarter  Day_Name  Week
0 2011-01-01      1    January        1  Saturday    52
1 2011-01-01      1    January        1  Saturday    52
2 2011-01-01      1    January        1  Saturday    52
3 2011-01-01      1    January        1  Saturday    52
4 2011-01-01      1    January        1  Saturday    52

In [43]:
duplicate_count = df.duplicated().sum()
print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [44]:
df['Shipping_Days'] = (df['ship_date'] - df['order_date']).dt.days

In [45]:
df[['order_date', 'ship_date', 'Shipping_Days']].head()

  order_date  ship_date  Shipping_Days
0 2011-01-01 2011-01-06              5
1 2011-01-01 2011-01-08              7
2 2011-01-01 2011-01-05              4
3 2011-01-01 2011-01-05              4
4 2011-01-01 2011-01-08              7

In [46]:
(df['Shipping_Days'] < 0).sum()

np.int64(0)

In [47]:
df.describe()

,order_date,ship_date,sales,quantity,discount,profit,shipping_cost,year,Month,Quarter,Day,Week,Shipping_Days
count,51267,51267,48638.000000,51267.000000,51267.000000,51267.000000,51267.00000,51267.000000,51267.000000,51267.000000,51267.000000,51267.0,51267.000000
mean,2013-05-12 06:30:39.077769472,2013-05-16 05:46:09.571069184,161.037090,3.476739,0.142917,28.634603,26.37037,2012.778005,7.525406,2.794039,15.785242,30.687967,3.969103
min,2011-01-01 00:00:00,2011-01-03 00:00:00,0.000000,1.000000,0.000000,-6599.978000,0.00000,2011.000000,1.000000,1.000000,1.000000,1.0,0.000000
25%,2012-06-19 00:00:00,2012-06-23 00:00:00,29.000000,2.000000,0.000000,0.000000,2.61000,2012.000000,5.000000,2.000000,8.000000,20.0,3.000000
50%,2013-07-08 00:00:00,2013-07-12 00:00:00,77.000000,3.000000,0.000000,9.240000,7.79000,2013.000000,8.000000,3.000000,16.000000,33.0,4.000000
75%,2014-05-22 00:00:00,2014-05-26 00:00:00,208.000000,5.000000,0.200000,36.810000,24.45000,2014.000000,10.000000,4.000000,23.000000,44.0,5.000000
max,2014-12-31 00:00:00,2015-01-07 00:00:00,999.000000,14.000000,0.850000,8399.976000,933.57000,2014.000000,12.000000,4.000000,31.000000,52.0,7.000000
std,NaN,NaN,201.105851,2.278981,0.212279,174.444774,57.23862,1.098533,3.298170,1.065578,8.741701,14.526732,1.729465

In [48]:
total_sales = df['sales'].sum()
print(f"Total Sales: {total_sales:,.2f}")

Total Sales: 7,832,522.00

In [49]:
total_profit = df['profit'].sum()
print(f"Total Profit: {total_profit:,.2f}")

Total Profit: 1,468,010.17

In [50]:
total_orders = df['order_id'].nunique()
print("Total Orders:", total_orders)

Total Orders: 25028

In [51]:
total_customers = df['customer_name'].nunique()
print("Total Customers:", total_customers)

Total Customers: 795

In [52]:
avg_order_value = total_sales / total_orders
print(f"Average Order Value: {avg_order_value:,.2f}")

Average Order Value: 312.95

In [53]:
top_products = (
    df.groupby('product_name')['sales']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(top_products)

product_name
Eldon File Cart, Single Width                         31063.0
Rogers File Cart, Single Width                        22645.0
Tenex File Cart, Single Width                         20778.0
Smead File Cart, Single Width                         20775.0
Office Star Executive Leather Armchair, Adjustable    19355.0
Fellowes Lockers, Industrial                          19172.0
Smead Lockers, Industrial                             18648.0
Hewlett Copy Machine, Color                           16849.0
Rogers Lockers, Blue                                  16494.0
Fellowes Lockers, Wire Frame                          16470.0
Name: sales, dtype: float64

In [54]:
top_customers = (
    df.groupby('customer_name')['sales']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(top_customers)

customer_name
John Grady          19483.0
Eric Murdock        19432.0
Maria Etezadi       18237.0
Theone Pippenger    17416.0
Dan Reichenbach     16705.0
Ben Ferrer          16661.0
Randy Bradley       16399.0
Mathew Reese        16125.0
Muhammed Yedwab     16091.0
Steven Ward         15984.0
Name: sales, dtype: float64

In [55]:
region_sales = (
    df.groupby('region')['sales']
      .sum()
      .sort_values(ascending=False)
)

print(region_sales)

region
Central           1805835.0
South             1030289.0
North              790546.0
Oceania            625313.0
EMEA               575296.0
Africa             537650.0
Southeast Asia     532172.0
North Asia         453686.0
West               424106.0
Central Asia       389506.0
East               366368.0
Caribbean          251441.0
Canada              50314.0
Name: sales, dtype: float64

In [56]:
category_sales = (
    df.groupby('category')['sales']
      .sum()
      .sort_values(ascending=False)
)

print(category_sales)

category
Office Supplies    2789121.0
Technology         2636796.0
Furniture          2406605.0
Name: sales, dtype: float64

In [57]:
monthly_sales = (
    df.groupby('Month_Name')['sales']
      .sum()
)

print(monthly_sales)

Month_Name
April        455594.0
August       784982.0
December     957117.0
February     339899.0
January      383414.0
July         488345.0
June         807184.0
March        466327.0
May          562178.0
November     988420.0
October      705696.0
September    893366.0
Name: sales, dtype: float64

In [58]:
monthly_sales = (
    df.groupby(['year', 'Month_Name'])['sales']
      .sum()
      .reset_index()
)

print(monthly_sales.head())

     year Month_Name     sales
0  2011.0      April   80698.0
1  2011.0     August  132065.0
2  2011.0   December  199654.0
3  2011.0   February   60757.0
4  2011.0    January   61996.0

In [59]:
market_sales = (
    df.groupby('market')['sales']
      .sum()
      .sort_values(ascending=False)
)

print(market_sales)

market
APAC      2000677.0
EU        1802357.0
LATAM     1562953.0
US        1303275.0
EMEA       575296.0
Africa     537650.0
Canada      50314.0
Name: sales, dtype: float64

In [60]:
profit_category = (
    df.groupby('category')['profit']
      .sum()
      .sort_values(ascending=False)
)

print(profit_category)

category
Technology         662851.44638
Office Supplies    518376.47030
Furniture          286782.25380
Name: profit, dtype: float64

In [61]:
shipping_analysis = (
    df.groupby('ship_mode')['Shipping_Days']
      .mean()
      .sort_values()
)

print(shipping_analysis)

ship_mode
Same Day          0.037394
First Class       2.181818
Second Class      3.230307
Standard Class    4.997952
Name: Shipping_Days, dtype: float64

In [62]:
segment_sales = (
    df.groupby('segment')['sales']
      .sum()
      .sort_values(ascending=False)
)

print(segment_sales)

segment
Consumer       4055782.0
Corporate      2369133.0
Home Office    1407607.0
Name: sales, dtype: float64

In [64]:
df.to_csv("Cleaned_SuperStoreOrders.csv", index=False)

In [65]:
import os

print(os.getcwd())

C:\Users\kapoo

In [66]:
import os

os.listdir()

['.anaconda',
 '.conda',
 '.condarc',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.spyder-py3',
 'anaconda3',
 'AppData',
 'Application Data',
 'Automated_Sales_Data_Cleaning.ipynb.ipynb',
 'cleaned',
 'Cleaned Data.txt',
 'Cleaned_SuperStoreOrders.csv',
 'Contacts',
 'Cookies',
 'Data.xlsx',
 'Documents',
 'Downloads',
 'Favorites',
 'Jedi',
 'Links',
 'Local Settings',
 'Microsoft',
 'MongoDB.ipynb',
 'Music',
 'My Documents',
 'name.txt',
 'NetHood',
 'NewData.xlsx',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{cf372c2e-6dd6-11f0-b00d-50bbb53576b9}.TM.blf',
 'NTUSER.DAT{cf372c2e-6dd6-11f0-b00d-50bbb53576b9}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{cf372c2e-6dd6-11f0-b00d-50bbb53576b9}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'NumPy.ipynb',
 'numpy.txt',
 'OneDrive',
 'PIYUSH KAPOOR.ipynb',
 'PiyushData.xlsx',
 'PrintHood',
 'Recent',
 'Sales_April_2019.csv.xlsx',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Untitled Folder 1',
 'Untitled.ipynb',
 'untitled.txt',
 'untitled0.py',
 'untitled1.txt',
 'Videos']

In [67]:
import os

os.listdir(os.getcwd())

['.anaconda',
 '.conda',
 '.condarc',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.spyder-py3',
 'anaconda3',
 'AppData',
 'Application Data',
 'Automated_Sales_Data_Cleaning.ipynb.ipynb',
 'cleaned',
 'Cleaned Data.txt',
 'Cleaned_SuperStoreOrders.csv',
 'Contacts',
 'Cookies',
 'Data.xlsx',
 'Documents',
 'Downloads',
 'Favorites',
 'Jedi',
 'Links',
 'Local Settings',
 'Microsoft',
 'MongoDB.ipynb',
 'Music',
 'My Documents',
 'name.txt',
 'NetHood',
 'NewData.xlsx',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{cf372c2e-6dd6-11f0-b00d-50bbb53576b9}.TM.blf',
 'NTUSER.DAT{cf372c2e-6dd6-11f0-b00d-50bbb53576b9}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{cf372c2e-6dd6-11f0-b00d-50bbb53576b9}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'NumPy.ipynb',
 'numpy.txt',
 'OneDrive',
 'PIYUSH KAPOOR.ipynb',
 'PiyushData.xlsx',
 'PrintHood',
 'Recent',
 'Sales_April_2019.csv.xlsx',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Untitled Folder 1',
 'Untitled.ipynb',
 'untitled.txt',
 'untitled0.py',
 'untitled1.txt',
 'Videos']

In [68]:
import os

print(os.path.abspath("Cleaned_SuperStoreOrders.csv"))

C:\Users\kapoo\Cleaned_SuperStoreOrders.csv

In [69]:
print(os.path.abspath("Cleaned_SuperStoreOrders.csv"))

C:\Users\kapoo\Cleaned_SuperStoreOrders.csv